import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { BsArrowDownCircle } from "react-icons/bs";
import { FaGithub, FaLinkedinIn } from "react-icons/fa";
import { useRef } from "react";
import Link from "next/link";
import Projects from "../components/Projects";

export default function Home() {
  const courseRef = useRef(null);
  const scrollToCourse = () =>
    courseRef.current.scrollIntoView({ behavior: "smooth" });
  const courseRef1 = useRef(null);
  const scrollToCourse1 = () =>
    courseRef1.current.scrollIntoView({ behavior: "smooth" });
  const courseRef2 = useRef(null);
  const scrollToCourse2 = () =>
    courseRef2.current.scrollIntoView({ behavior: "smooth" });

  return (
    <div className=" bg-gradient-to-r from-slate-800 via-slate-600 to-slate-800">
      <Head>
        <title></title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="  max-w-screen-2xl mx-auto">
        <section
          ref={courseRef2}
          className="min-h-screen flex items-center justify-center "
        >
          <div>
            {" "}
            <div className="text-8xl font-mono text-white text-center pt-20 uppercase  ">
              <a> Hi I&apos;m Justin Kim</a>
            </div>
            <div className="pt-20  text-white  text-2xl font-mono text-center">
              I am a Software Engineer Pursuing a Bachelors Degree in Computer
              Science at Santa Clara Univerity.
            </div>
            <div className="flex gap-4 justify-center items-center text-white mt-10">
              <a
                target="_blank"
                href="https://github.com/justokim"
                rel="noopener noreferrer"
              >
                {" "}
                <FaGithub className=" text-slate-800 w-8 h-8 hover:w-10 hover:h-10 duration-150 ease-in" />
              </a>

              <a
                target="_blank"
                href="https://github.com/justokim"
                rel="noopener noreferrer"
              >
                <FaLinkedinIn className="w-8 h-8 text-slate-800  duration-150 ease-in hover:w-10 hover:h-10 " />
              </a>
            </div>
            <div className="flex justify-center items-center pt-10 gap-2 text-white text-xl">
              <a className="font-mono text-2xl">Learn More</a>
              <BsArrowDownCircle
                className="mt-1 animate-bounce z-0 w-8 h-8 cursor-pointer "
                onClick={scrollToCourse}
              />
            </div>
          </div>
        </section>
        <section className="min-h-screen flex items-center justify-center">
          <div className="w-full h-fullfont-mono">
            <a
              ref={courseRef}
              className=" ml-24 text-7xl font-mono text-white border-b-2 "
            >
              About Me
            </a>
            <div className="grid grid-cols-2 mt-20 items-center place-items-center">
              <div className="pl-24 text-xl text-white space-y-4">
                <p>
                  Hello there! My name is Justin Kim and I am currently a Junior
                  at Santa Clara University studying Computer Science.
                </p>
                <p>
                  As someone who was introducted to the world of Computer
                  Science during my freshman year of college undergrad, I have
                  since fell in love and have been engaging with it ever since.
                  As basic html css pages turned into more interactive pages and
                  later into full scale websites, I have taught myself full
                  stack web-development along the way. From being on the
                  internet my whole life to now understanding the how and why of
                  the intricacies of every single website from the backend to
                  the frontend has motivated me to keep on learning and not just
                  in web development but in a multidude of topics such as
                  Software Development, Data Science, Cyber Security, etc.
                </p>
                <p>
                  Outside of school, I love to keep myself busy by spending time
                  with my family, playing poker, and practicing the cello and my
                  golf swing!
                </p>
              </div>
              <div className="">
                <Image
                  src="/people/justo.jpg"
                  alt="picture"
                  objectFit="contain"
                  height={500}
                  width={700}
                />
              </div>
            </div>
          </div>
        </section>
        <section className="min-h-screen">
          <div className="mx-auto w-full h-full font-mono">
            <a
              ref={courseRef1}
              className=" ml-24 text-7xl font-mono text-white border-b-2 "
            >
              Projects
            </a>
            <Projects />
          </div>
        </section>
        <section className="max-h-full py-24">
          <div className="text-xl text-center text-white font-mono">
            Any Questions? Contact me at
          </div>
          <div className="text-2xl text-center text-blue-500 underline font-mono pt-2">
            <a href="mailto:justinkim707@gmail.com" className="cursor-pointer">
              justinkim707@gmail.com
            </a>
          </div>
          <div className="flex gap-4 justify-center items-center text-white mt-10">
            <a
              target="_blank"
              href="https://github.com/justokim"
              rel="noopener noreferrer"
            >
              {" "}
              <FaGithub className=" text-slate-800 w-8 h-8 hover:w-10 hover:h-10 duration-150 ease-in" />
            </a>

            <a
              target="_blank"
              href="https://github.com/justokim"
              rel="noopener noreferrer"
            >
              <FaLinkedinIn className="w-8 h-8 text-slate-800  duration-150 ease-in hover:w-10 hover:h-10 " />
            </a>
          </div>
        </section>
      </main>
    </div>
  );
}
